/** Warm Culinary Editorial design tokens (see stitch_mealcaster/warm_culinary_editorial/DESIGN.md). */
export default {
  content: { relative: true, files: ['./index.html', './src/**/*.{svelte,js}'] },
  theme: {
    extend: {
      colors: {
        background: '#fcf9f3',
        surface: '#fcf9f3',
        'surface-dim': '#dcdad4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'surface-variant': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#424843',
        outline: '#727973',
        'outline-variant': '#c2c8c1',
        primary: '#32533f',
        'on-primary': '#ffffff',
        'primary-container': '#4a6b56',
        'primary-fixed': '#c6ebd1',
        secondary: '#a23e18',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe8357',
        'secondary-fixed': '#ffdbcf',
        tertiary: '#674600',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-sm': ['13px', { lineHeight: '18px' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        gutter: '1.25rem',
        'gutter-desktop': '1.5rem',
      },
      boxShadow: {
        card: '0 2px 8px -2px rgba(50, 40, 30, 0.04), 0 1px 3px 0 rgba(50, 40, 30, 0.02)',
        lift: '0 12px 24px -6px rgba(45, 38, 30, 0.08), 0 4px 10px -2px rgba(45, 38, 30, 0.04)',
        header: '0 1px 8px rgba(50, 40, 30, 0.05)',
      },
    },
  },
  plugins: [],
};
